version: "3.2"
services:
  app:
    container_name: Lets Find
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: LetsFind_DATABASE
    image: mongo
   
    ports:
      - "27017:27017"